AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Description: "Try to merge pull request automatically and notify its result to slack when a review is requested"

Resources:
  GitHubMergeBot:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: github-merge-bot
      Runtime: go1.x
      Timeout: 10
      CodeUri: src/
      Handler: github-merge-bot
      Role: arn:aws:iam::your-account-id:role/your-role-name
      Environment:
        Variables:
          GITHUB_ACCESS_TOKEN: your_github_access_token
          SLACK_INCOMING_WEBHOOK_URL: https://hooks.slack.com/services/your-incoming-webhook-url
      Events:
        GitHubMergeBotTrigger:
          Type: Api
          Properties:
            Path: /
            Method: post
